package FindTheDifference;

import java.util.Arrays;
import java.util.HashSet;

/**
 * 389. Find the Difference
 *
 * Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s
 * and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
    public char findTheDifference(String s, String t) {
        int[] alphabet = new int[26];
        for(char c:s.toCharArray()) {
            alphabet[c-'a']++;
        }

        for(char c:t.toCharArray()) {
            alphabet[c-'a']--;
            if(alphabet[c-'a'] < 0)
                return c;
        }

        return ' ';
    }
}
